name: CI/CD Pipeline - Deploy to AWS EC2

on:
  push:
    branches:
      - monitoring

env:
  IMAGE_NAME: churn-prediction
  TAG: mo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG .

      - name: Tag and Push to ECR
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          IMAGE_NAME: churn-prediction
          TAG: mo
        run: |
          echo "ECR_REGISTRY=$ECR_REGISTRY"
          echo "IMAGE_NAME=$IMAGE_NAME"
          echo "TAG=$TAG"
          docker tag $IMAGE_NAME:$TAG $ECR_REGISTRY/$IMAGE_NAME:$TAG
          docker push $ECR_REGISTRY/$IMAGE_NAME:$TAG

      - name: Write SSH key to file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy app to EC2
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ env.AWS_REGION }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          TAG: ${{ env.TAG }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
            echo "✅ Logged into EC2"
  
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 060795916912.dkr.ecr.us-east-1.amazonaws.com
            echo "✅ Logged into ECR"
  
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            echo "✅ Pulled image from ECR"
  
            docker rm -f myapp || true
            docker rm -f $(docker ps -aq)
            docker rmi -f $(docker images -q)
            echo "IMAGE NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
            docker run -d --name myapp -p 80:8000 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            docker logs myapp
            echo "✅ Deployed app to EC2"
          EOF
